apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qyuanqgh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qyuanqgh:f0b603447a1b8fba2436ba9492955146370cf6c5@sha256:04131da3a7db1552b103ac90b2f23f45f2507012660ae1d7cd6b9a96b43db8ac
          name: container-image
